easy_admin:
    site_name: Admin
    design:
      menu:
        - { label: 'Public Homepage', route: 'home' }
        - User
        - Article
        - SummaryArticle
        - Payment
        - Discount
    entities:
        # List the entity class name you want to manage
      Discount:
        class: App\Entity\Discount
        label: 'Discounts'
      User:
        class: App\Entity\User
        label: 'Users'
        form:
          fields:
            - fullName
            - phoneNumber
            - email
            - paid
            - {property: 'plainPassword', label: 'Password', type: 'password'}
            - {property: 'national_code', label: 'National code', type: 'text'}
            - {property: roles, label: 'User roles', help: 'ROLE_SEND_ARTICLE for giving access sending article.'}

      Payment:
        label: 'Payments'
        class: App\Entity\Payment
      SummaryArticle:
        label: 'Summary of articles'
        class: App\Entity\SummaryArticle
        list:
          fields: ['title', 'user','paid','accepted','reviewed']
          actions:
            - {name: 'download_file', label: 'Download File', type: 'route'}
      Article:
        label: 'Articles'
        class: App\Entity\Article
        list:
          fields: ['summary','user','paid']
          actions:
            - {name: 'download_file', label: 'Download File', type: 'route'}

