easy_admin:
    site_name: Admin
    design:
      menu:
        - { label: 'Public Homepage', route: 'home' }
        - User
        - Article
        - SummaryArticle
        - Payment
        - RegistrationType
    entities:
        # List the entity class name you want to manage

      User:
        class: App\Entity\User
        label: 'Users'
        form:
          fields:
            - fullName
            - phoneNumber
            - email
            - registrationType
            - paid
            - {property: 'plainPassword', label: 'Password', type: 'password'}
            - {property: roles, label: 'User roles', help: 'ROLE_SEND_ARTICLE for giving access sending article.'}

      RegistrationType:
        class: App\Entity\RegistrationType
        label: 'Registration Types'
        form:
          fields:
            - price
            - name
            - description
            - {property: roles, label: 'User roles', help: 'ROLE_SEND_ARTICLE for giving access sending article.'}

      Payment:
        label: 'Payments'
        class: App\Entity\Payment
      SummaryArticle:
        label: 'Summary of articles'
        class: App\Entity\SummaryArticle
        list:
          fields: ['title', 'user','state']
          actions:
            - {name: 'download_file', label: 'Download File', type: 'route'}
            - {name: 'checking_article', label: 'Check/Confirm', type: 'route'}
      Article:
        label: 'Articles'
        class: App\Entity\Article
        list:
          fields: ['summary','user','state']
          actions:
            - {name: 'download_file', label: 'Download File', type: 'route'}
            - {name: 'checking_article', label: 'Check/Confirm', type: 'route'}

