
 The following SQL statements will be executed:

     CREATE TABLE summary_article (id INTEGER NOT NULL, user_id INTEGER DEFAULT NULL, article_id INTEGER DEFAULT NULL, payment_id INTEGER DEFAULT NULL, title VARCHAR(255) NOT NULL, reviewed BOOLEAN NOT NULL, accepted BOOLEAN NOT NULL, paid BOOLEAN NOT NULL, file VARCHAR(255) NOT NULL, PRIMARY KEY(id), CONSTRAINT FK_7DAAE07DA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_7DAAE07D7294869C FOREIGN KEY (article_id) REFERENCES article (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_7DAAE07D4C3A3BB FOREIGN KEY (payment_id) REFERENCES payment (id) NOT DEFERRABLE INITIALLY IMMEDIATE);
     CREATE INDEX IDX_7DAAE07DA76ED395 ON summary_article (user_id);
     CREATE UNIQUE INDEX UNIQ_7DAAE07D7294869C ON summary_article (article_id);
     CREATE UNIQUE INDEX UNIQ_7DAAE07D4C3A3BB ON summary_article (payment_id);
     CREATE TABLE reset_password_token (hash VARCHAR(255) NOT NULL, user_id INTEGER DEFAULT NULL, expire_time DATETIME NOT NULL, PRIMARY KEY(hash), CONSTRAINT FK_452C9EC5A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) NOT DEFERRABLE INITIALLY IMMEDIATE);
     CREATE INDEX IDX_452C9EC5A76ED395 ON reset_password_token (user_id);
     CREATE TABLE article (id INTEGER NOT NULL, user_id INTEGER DEFAULT NULL, summary_id INTEGER DEFAULT NULL, payment_id INTEGER DEFAULT NULL, file VARCHAR(255) NOT NULL, paid BOOLEAN NOT NULL, PRIMARY KEY(id), CONSTRAINT FK_23A0E66A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_23A0E662AC2D45C FOREIGN KEY (summary_id) REFERENCES summary_article (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_23A0E664C3A3BB FOREIGN KEY (payment_id) REFERENCES payment (id) NOT DEFERRABLE INITIALLY IMMEDIATE);
     CREATE INDEX IDX_23A0E66A76ED395 ON article (user_id);
     CREATE UNIQUE INDEX UNIQ_23A0E662AC2D45C ON article (summary_id);
     CREATE UNIQUE INDEX UNIQ_23A0E664C3A3BB ON article (payment_id);
     CREATE TABLE discount (id INTEGER NOT NULL, user_id INTEGER DEFAULT NULL, payment_id INTEGER DEFAULT NULL, used BOOLEAN NOT NULL, price VARCHAR(255) NOT NULL, PRIMARY KEY(id), CONSTRAINT FK_E1E0B40EA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_E1E0B40E4C3A3BB FOREIGN KEY (payment_id) REFERENCES payment (id) NOT DEFERRABLE INITIALLY IMMEDIATE);
     CREATE INDEX IDX_E1E0B40EA76ED395 ON discount (user_id);
     CREATE INDEX IDX_E1E0B40E4C3A3BB ON discount (payment_id);
     CREATE TABLE payment (id INTEGER NOT NULL, user_id INTEGER DEFAULT NULL, reference_id VARCHAR(255) DEFAULT NULL, price VARCHAR(255) NOT NULL, online_payment_price VARCHAR(255) NOT NULL, state INTEGER NOT NULL, metadata CLOB NOT NULL --(DC2Type:json)
, done BOOLEAN NOT NULL, creation_date DATETIME NOT NULL, done_date DATETIME DEFAULT NULL, PRIMARY KEY(id), CONSTRAINT FK_6D28840DA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) NOT DEFERRABLE INITIALLY IMMEDIATE);
     CREATE INDEX IDX_6D28840DA76ED395 ON payment (user_id);
     CREATE TABLE user (id INTEGER NOT NULL, first_name VARCHAR(255) NOT NULL, lastname VARCHAR(255) NOT NULL, phone_number VARCHAR(255) NOT NULL, national_code VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, roles CLOB NOT NULL --(DC2Type:array)
, paid BOOLEAN DEFAULT '0' NOT NULL, PRIMARY KEY(id));
     CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON user (email);
